### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/homebrew-install#3]
Hi @danielbayley, we need to adjust a few things first to move forward, ok? ✨

First, we need to update the screenshot!

Can you take a single capture at the closest possible resolution to 1728x1117?

We also need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories, [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by danielbayley** [comment]
@luxonauta I’m guessing this issue was auto-generated? I don’t think these changes apply to this particular repo, since it’s only for the Home`brew` installers…

**Comment by luxonauta** [comment]
I believe this is the case! I'm closing the Issue.
